### ISSUE TITLE
Multiple pinboards

### ISSUE THREAD

**Issue by bytersproblem** [kookma/TW-Pinboard#1]
This is a great plugin for TiddlyWiki!
Is that possible  to have more than one pinboard?

**Comment by kookma** [comment]
Yes, you need to hack the https://kookma.github.io/TW-Pinboard/#%24%3A%2Fplugins%2Fkookma%2Fpinboard%2Fmacros%2Fst-note tiddler

Right now board is created by calling `pinboard-ui`

```
\define pinboard-ui()
<$list filter="[tag[pin]!tag[done]]">
<$macrocall $name="_st_single_note" tiddler=<<currentTiddler>> priority={{!!priority}}/>
</$list>
\end
```

if you modify it as below

```
\define pinboard-ui(mytag:pin)
<$list filter="[tag[$mytag$]!tag[done]]">
<$macrocall $name="_st_single_note" tiddler=<<currentTiddler>> priority={{!!priority}}/>
</$list>
\end
```

Then you can have second and third pinboard each created by a tag like

`<<pinboard-ui  work>>` and `<<pinboard-ui  personal>>`

These commands create pinboard from all tiddlers tagged with `work` and `personal`.

**Comment by bytersproblem** [comment]
Thanks, Mohammad, it solved it!
