### ISSUE TITLE
Plugin won't install on 5.2.7

### ISSUE THREAD

**Issue by brandonwsaxe** [kookma/TW-Pinboard#2]
I'm new to TiddlyWiki. I've managed to install a couple other plugins manually by dragging and dropping the links into my wiki. However, nothing happens when I drag and drop Pinboard into my wiki.

**Comment by kookma** [comment]
First try this on [ tiddlywiki.com](https://tiddlywiki.com)

1. open https://tiddlywiki.com
2. open https://kookma.github.io/TW-Pinboard/
3. drag and drop [$:/plugins/kookma/pinboard](https://kookma.github.io/TW-Pinboard/#%24%3A%2Fplugins%2Fkookma%2Fpinboard) into [tiddlywiki.com](https://tiddlywiki.com)

For me the above procedure works.
