### ISSUE TITLE
Plugins like this can be a layout

### ISSUE THREAD

**Issue by linonetwo** [kookma/TW-Pinboard#3]
Then it will feels like a brand new app.

Recently I'm try to make new layouts if I can, so tw will have many apps that share same datasources.

Most importantly, layout is like a drawer that you can put featues inside, and won't take too much space and time. Like I put echarts inside the visualization dashboard layout, because I find there is no much space on sidebar or home tiddler to put so much charts, and charts' calculation is slow down my wiki. After place them in a layout, it feels better.

Just some recommendation, when I come cross this.

**Comment by kookma** [comment]
Great idea! I welcome a PR.
